### ISSUE TITLE
Android Voice Audio Distortion

### ISSUE THREAD

**Issue by Henry-Graves** [Hubs-Foundation/hubs#5227]
**Description**
Voice audio becomes very distorted after being in a room for a few minutes on certain devices. Fixed by refreshing the page or by just waiting 30 seconds - 1 minute for the audio quality to go back to normal.
It's hard to explain the audio, but we have a [video for reference.](https://youtu.be/Z0KS7EMr-mY)

**To Reproduce**
1. Using the specified hardware, open any Hubs scene.
2. Have a second person in the room speaking or playing audio.
3. On the specified hardware, monitor the audio of the second person. We haven't been able to pin down the exact time it takes for this to happen, sometimes it's within a few minutes and other times it can take more than 10.

**Hardware**
 - Device: Galaxy S20 Ultra
 - OS: Android 11 and 12
 - Browser: Chrome (up to date version)
 - Happens on mobile data and wifi connections

**Comment by takahirox** [comment]
Hi, thanks for the problem report.

Unfortunately I couldn't reproduce the problem on my Samsung Galaxy S8+ Android Chrome.

Two questions to investigate the problem more.

1. Does the problem happen in any scenes? Or only specific scenes? If only specific scenes, can you share them with us?
2. If you have other Android devices, can you reproduce the problem with them?

**Comment by vincentfretin** [comment]
The issue you are showing on the video may not be the android phone at all, it could be the other participant upload bandwidth or the other participant high cpu usage. Did you reproduce the issue with another participant?

This talk was great https://www.youtube.com/watch?v=t3GVVXflgSg explaining the causes of robotic audio, accelerated and decelerated audio, low resolution video, low frame rate video.

**Comment by Henry-Graves** [comment]
@takahirox 
1. The problem happens in all of the scenes we've tried, they're all ones that we've built though so we will test on the default Hubs scene soon.
2. We have tested on a OnePlus 6 and Galaxy Z Fold 3 and haven't been able to reproduce the problem on them.

@vincentfretin 
Thank you for the video!
In our case, the issue is not on the speaking participants' end as we have four people on separate networks, the audio bug is only on one person's receiving end. He tells us when the audio he receives starts bugging out, and we can still hear him speaking with no drop in quality. My theory right now is that it's a hardware issue specific to his phone (maybe CPU usage?) and how it is handling audio processes.

Looking back at the demo video I posted - it doesn't seem like packet loss because of how our demo's audio distortion very gradually increases, there is no cutting out or accelerating of audio, and the pitch of the voice speaking is being lowered but it's not being "robotically" interpolated as it usually is with packet loss. It's really strange, I've been in thousands of hours of WebRTC calls and never heard anything like this.

We'll test factors strategically over our next few meetings and will report any progress.

**Comment by takahirox** [comment]
@Henry-Graves Hi, thanks for the answers. Do you mind if checking the "Disable audio left/right panning" option checkbox in the preferences and checking if the problem can be mitigated? You can find the option in "More" - "Preferences" - "Audio" tab. I guess this problem can be strongly related to #5057.
