### ISSUE TITLE
Mirror object rendering issues on iPhone

### ISSUE THREAD

**Issue by Henry-Graves** [Hubs-Foundation/hubs#5422]
**Description**
There are rendering issues whenever a mirror is in view on iPhone.

In [video 1](https://drive.google.com/file/d/1lOq3IVe6iCz0PzSOe63AWBW8G-JYhFRJ/view), I turn towards a flat mirror on a wall. Once it's within my FOV, everything except for the people, the placed objects in the scene, the mirror, and the reflected scene in the mirror turn black until I turn away or go behind the mirror to the non-reflective side.

In [video 2](https://drive.google.com/file/d/1CLq1idVztXVNQpLKYmiyTc898rv8GixW/view) the scene doesn't go black, but still has issues. The video begins behind a mirror, goes through it, then turns around.

**To Reproduce**
1. On a client with the mirrors from hubs-cloud, create a scene with a mirror.
2. Using similar hardware to what's listed below, enter a room with the created scene.
3. Move and look around the mirror.

**Hardware & Browsers**
- iPhone 10 & 13 Pro (2018 MacBook and iPad Air don't have the issue)
- iOS 15.4.1
- Chrome, Safari, Firefox

**Comment by emclaren** [comment]
Labelling this as a P3 issue. It is on our radar, and we are doing improvements for iPhone and this might improve the experience. If other people are encountering this, please let us know.

**Comment by Henry-Graves** [comment]
Thanks, also for clarity we were able to replicate this on four separate devices (iPhone 10s and 13 Pros) and multiple different rooms & scenes with mirrors on hubs.mozilla.com as well as our custom client.
