### ISSUE TITLE
Spacebar Menu Scale and Rotate Buttons Do Nothing When Interacted  With

### ISSUE THREAD

**Issue by Exairnous** [Hubs-Foundation/hubs#6496]
**Description**
Objects can't be manipulated via the scale and rotate buttons from the spacebar menu anymore.

**To Reproduce**
1. Enter a Hubs room.
2. Spawn a duck with the /duck chat command.
3. Hover over the duck and press and hold the spacebar to bring up the menu.
4. Click and drag on the scale or rotate buttons while holding the spacebar.
5. See that the duck moves instead of scaling or rotating.

**Expected behavior**
The object should be scaled or rotated, depending on which button is interacted with.

**Video**
https://github.com/user-attachments/assets/ed28a602-5af2-4ff6-aba6-6bf401f1972e
Video courtesy of mr. lion on Discord.

**Hardware** 
 - Device: Laptop
 - OS: GNU/Linux
 - Browser: Chromium

**Additional context**
~~Potentially caused by #6495~~
Potentially caused by #6487
~~Physics also seems to be affected by this bug.  Objects can no longer be thrown and the gravity/drop to floor button on the spacebar button does nothing if the object has been moved.~~  Update: the physics issues are probably a separate bug and have been reported in #6503, #6504, #6505

**Comment by DougReeder** [comment]
I used those so seldom that I've forgotten how they are supposed to work. Do we have any videos of the rotate and scale buttons working properly?

**Comment by Exairnous** [comment]
@DougReeder
While not the greatest quality, videos of the buttons working can be found in the description of this issue: https://github.com/Hubs-Foundation/hubs/issues/6405

**Comment by Exairnous** [comment]
Fixed by https://github.com/Hubs-Foundation/hubs/pull/6515
